In [15]:
import pandas as pd

file_path = r"C:\Users\parsh\Desktop\Data science\people.csv.xlsx"
df = pd.read_excel(file_path)
print(df)

    Index          User Id First Name  Last Name     Sex  \
0       1  88F7B33d2bcf9f5     Shelby    Terrell    Male
1       2  f90cD3E76f1A9b9    Phillip    Summers  Female
2       3  DbeAb8CcdfeFC2c   Kristine     Travis    Male
3       4  A31Bee3c201ef58        NaN   Martinez    Male
4       5  1bA7A3dc874da3c       Lori       Todd    Male
..    ...              ...        ...        ...     ...
95     96  5eFda7caAeB260E     Dennis     Barnes  Female
96     97  CCbFce93d3720bE      Steve  Patterson  Female
97     98  2fEc528aFAF0b69     Wesley       Bray    Male
98     99  Adc7ad9B6e4A1Fe     Summer   Oconnell  Female
99    100  b8D0aD3490FC7e1     Mariah    Bernard    Male

                         Email                   Phone Date of birth  \
0         elijah57@example.net  001-084-906-7849x73518    1945-10-26
1        bethany14@example.com       214.112.6044x4913    1910-03-24
2        bthompson@example.com            277.609.7938    1992-07-02
3    kaitlinkaiser@example.com            584.094.6111    2017-08-03
4                          NaN       689-207-3558x7233    1938-12-01
..                         ...                     ...           ...
95         bmartin@example.org    001-095-524-2112x257    1954-07-30
96       latasha46@example.net        001-865-478-5157    1932-04-29
97        regina11@example.org      995-542-3004x76800    1994-12-28
98  alexiscantrell@example.org    001-273-685-6932x092    2012-04-12
99       pcopeland@example.org     (341)594-6554x44657    2016-11-15

                Job Title
0         Games developer
1                     NaN
2               Homeopath
3       Market researcher
4      Veterinary surgeon
..                    ...
95      Software engineer
96              Barrister
97         Police officer
98   Broadcast journalist
99  IT sales professional

[100 rows x 9 columns]

In [16]:
df.isnull()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False

In [ ]:
df.dropna(axis=1)  #this function will drop the columns that have no values

    Index     Sex                   Phone
0       1    Male  001-084-906-7849x73518
1       2  Female       214.112.6044x4913
2       3    Male            277.609.7938
3       4    Male            584.094.6111
4       5    Male       689-207-3558x7233
..    ...     ...                     ...
95     96  Female    001-095-524-2112x257
96     97  Female        001-865-478-5157
97     98    Male      995-542-3004x76800
98     99  Female    001-273-685-6932x092
99    100    Male     (341)594-6554x44657

[100 rows x 3 columns]

In [19]:
df.dropna(axis=0)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
5,6,bfDD7CDEF5D865B,Erin,Day,Male,tconner@example.org,001-171-649-9856x5553,2015-10-28,Waste management officer
6,7,bE9EEf34cB72AF7,Katherine,Buck,Female,conniecowan@example.com,+1-773-151-6685x49162,1989-01-22,Intelligence analyst
7,8,2EFC6A4e77FaEaC,Ricardo,Hinton,Male,wyattbishop@example.com,001-447-699-7998x88612,1924-03-26,Hydrogeologist
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool